name = "herbaprima"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[site]
bucket = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "herbaprima-db"
database_id = "b2e3cd1b-4744-447f-b51a-244b77494cfd"
